In [6]:
import torch
import torch.nn as nn
from collections import OrderedDict
import matplotlib.pyplot as plt

model = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 3)),      # first hidden layer with 4 neurons
    ('tanh', nn.Tanh()),              # Tanh activation function
    # ('hidden2', nn.Linear(3, 4)),     # second hidden layer with 4 neurons
    # ('relu', nn.ReLU()),              # ReLU activation function
    ('output', nn.Linear(3, 1)),      # output layer with 1 neuron
    ('sigmoid', nn.Sigmoid())         # sigmoid activation function
]))
print(model)
data_in = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in)

data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)


criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model.parameters(), lr=0.01)

# Define the number of epochs for training
num_epochs = 1000

# Lists to store loss values for visualization
losses = []

# Training loop
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(data_in)
    loss = criterion1(outputs, data_target1)
    
    # Backward pass and optimization
    optimizer1.zero_grad()
    loss.backward()
    optimizer1.step()
    
    # Store the loss value for visualization
    losses.append(loss.item())
    
    # Print the loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')


print('Outputs:')
print(outputs)

with torch.no_grad():
    predictions = torch.round(model(data_in))

# Calculate accuracy
correct_predictions = (predictions.squeeze() == data_target1[:, 0]).sum().item()
total_samples = len(data_target1)
accuracy = correct_predictions / total_samples

# Print accuracy
print(f'Overall Accuracy: {accuracy * 100:.2f}%')


# Print model weights
for name, param in model.named_parameters():
    if param.requires_grad:
        print(f'Layer: {name}, Weights: {param.data}')

Sequential(
  (hidden): Linear(in_features=2, out_features=3, bias=True)
  (tanh): Tanh()
  (output): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Epoch [100/1000], Loss: 0.2418
Epoch [200/1000], Loss: 0.2397
Epoch [300/1000], Loss: 0.2379
Epoch [400/1000], Loss: 0.2363
Epoch [500/1000], Loss: 0.2349
Epoch [600/1000], Loss: 0.2337
Epoch [700/1000], Loss: 0.2326
Epoch [800/1000], Loss: 0.2315
Epoch [900/1000], Loss: 0.2306
Epoch [1000/1000], Loss: 0.2297
Outputs:
tensor([[0.3649],
        [0.3952],
        [0.3773],
        [0.4025]], grad_fn=<SigmoidBackward0>)
Overall Accuracy: 75.00%
Layer: hidden.weight, Weights: tensor([[ 0.3911,  0.0205],
        [-0.6516, -0.3549],
        [ 0.1180,  0.4937]])
Layer: hidden.bias, Weights: tensor([0.2549, 0.2183, 0.2098])
Layer: output.weight, Weights: tensor([[-0.2181, -0.16

In [46]:
import torch
import torch.nn as nn
from collections import OrderedDict
import matplotlib.pyplot as plt

model = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 3)),      # first hidden layer with 2 neurons
    ('sigmoid', nn.Sigmoid()),        # sigmoid activation function
    ('output', nn.Linear(3, 1)),     # second hidden layer with 1 neurons
    ('tanh', nn.Tanh())           # Tanh activation function
    
]))
print(model)
data_in = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in)

data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)

criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model.parameters(), lr=0.01)

# Define the number of epochs for training
num_epochs = 1000

# Lists to store loss values for visualization
losses = []

# Training loop
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(data_in)
    loss = criterion1(outputs, data_target)
    
    # Backward pass and optimization
    optimizer1.zero_grad()
    loss.backward()
    optimizer1.step()
    
    # Store the loss value for visualization
    losses.append(loss.item())
    
    # Print the loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')


print('Outputs:')
print(outputs)

with torch.no_grad():
    predictions = torch.round(model(data_in))

# Calculate accuracy
correct_predictions = (predictions.squeeze() == data_target1[:, 0]).sum().item()
total_samples = len(data_target1)
accuracy = correct_predictions / total_samples

# Print accuracy
print(f'Overall Accuracy: {accuracy * 100:.2f}%')

# Print model weights
for name, param in model.named_parameters():
    if param.requires_grad:
        print(f'Layer: {name}, Weights: {param.data}')

Sequential(
  (hidden): Linear(in_features=2, out_features=3, bias=True)
  (sigmoid): Sigmoid()
  (output): Linear(in_features=3, out_features=1, bias=True)
  (tanh): Tanh()
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Epoch [100/1000], Loss: 0.2507
Epoch [200/1000], Loss: 0.2505
Epoch [300/1000], Loss: 0.2505
Epoch [400/1000], Loss: 0.2505
Epoch [500/1000], Loss: 0.2504
Epoch [600/1000], Loss: 0.2504
Epoch [700/1000], Loss: 0.2504
Epoch [800/1000], Loss: 0.2503
Epoch [900/1000], Loss: 0.2503
Epoch [1000/1000], Loss: 0.2503
Outputs:
tensor([[0.4934],
        [0.4919],
        [0.5076],
        [0.5070]], grad_fn=<TanhBackward0>)
Overall Accuracy: 75.00%
Layer: hidden.weight, Weights: tensor([[ 0.2844, -0.6668],
        [ 0.1879,  0.4461],
        [-0.3852,  0.3811]])
Layer: hidden.bias, Weights: tensor([0.6907, 0.6839, 0.3660])
Layer: output.weight, Weights: tensor([[0.2926, 0.3589, 0

In [45]:
import torch
import torch.nn as nn
from collections import OrderedDict
import matplotlib.pyplot as plt

model = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 4)),      # first hidden layer with 4 neurons
    ('relu', nn.ReLU()),              # ReLU activation function
    ('output', nn.Linear(4, 1)),      # output layer with 1 neuron
    ('sigmoid', nn.Sigmoid())         # sigmoid activation function
]))
print(model)
data_in = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in)
data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)


criterion1 = nn.BCELoss()
optimizer1 = torch.optim.SGD(model.parameters(), lr=0.01)

# Define the number of epochs for training
num_epochs = 1000

# Lists to store loss values for visualization
losses = []

# Training loop
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(data_in)
    loss = criterion1(outputs, data_target)
    
    # Backward pass and optimization
    optimizer1.zero_grad()
    loss.backward()
    optimizer1.step()
    
    # Store the loss value for visualization
    losses.append(loss.item())
    
    # Print the loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')


print('Outputs:')
print(outputs)

with torch.no_grad():
    predictions = torch.round(model(data_in))

# Calculate accuracy
correct_predictions = (predictions.squeeze() == data_target1[:, 0]).sum().item()
total_samples = len(data_target1)
accuracy = correct_predictions / total_samples

# Print accuracy
print(f'Overall Accuracy: {accuracy * 100:.2f}%')


# Print model weights
for name, param in model.named_parameters():
    if param.requires_grad:
        print(f'Layer: {name}, Weights: {param.data}')

Sequential(
  (hidden): Linear(in_features=2, out_features=4, bias=True)
  (relu): ReLU()
  (output): Linear(in_features=4, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Epoch [100/1000], Loss: 0.6711
Epoch [200/1000], Loss: 0.6621
Epoch [300/1000], Loss: 0.6539
Epoch [400/1000], Loss: 0.6456
Epoch [500/1000], Loss: 0.6367
Epoch [600/1000], Loss: 0.6270
Epoch [700/1000], Loss: 0.6168
Epoch [800/1000], Loss: 0.6060
Epoch [900/1000], Loss: 0.5947
Epoch [1000/1000], Loss: 0.5827
Outputs:
tensor([[0.3681],
        [0.5269],
        [0.5542],
        [0.4732]], grad_fn=<SigmoidBackward0>)
Overall Accuracy: 25.00%
Layer: hidden.weight, Weights: tensor([[ 0.0751,  0.5791],
        [-0.0290, -0.1753],
        [-0.7937, -0.7929],
        [ 0.4963,  0.4002]])
Layer: hidden.bias, Weights: tensor([-0.0752,  0.4792,  0.7933, -0.3999])
Layer: output.